version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "4001:80"  # Mở cổng 4001 cho frontend
    restart: always
    networks:
      - websocket-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "4000:4000"  # Mở cổng 4000 cho backend (WebSocket server)
    restart: always
    networks:
      - websocket-network

networks:
  websocket-network:
    driver: bridge
